"""empty message

Revision ID: 179796f28313
Revises: 9e3748704a74
Create Date: 2024-06-12 12:47:49.895540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '179796f28313'
down_revision: Union[str, None] = '9e3748704a74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('requests', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'updated_at')
    op.drop_column('requests', 'created_at')
    # ### end Alembic commands ###
