"""empty message

Revision ID: b5ac87aef5dc
Revises: 179796f28313
Create Date: 2024-06-12 15:08:05.256741

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b5ac87aef5dc"
down_revision: Union[str, None] = "179796f28313"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("books", "author")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "books", sa.Column("author", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
